// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: tracker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на синхронизацию данных из Apple/Samsung Health
type SyncHealthDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // Идентификатор устройства
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`                         // Дата в формате YYYY-MM-DD
	Sleep         *SleepData             `protobuf:"bytes,3,opt,name=sleep,proto3" json:"sleep,omitempty"`                       // Данные о сне
	Activity      *ActivityData          `protobuf:"bytes,4,opt,name=activity,proto3" json:"activity,omitempty"`                 // Данные об активности (спорт)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncHealthDataRequest) Reset() {
	*x = SyncHealthDataRequest{}
	mi := &file_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncHealthDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncHealthDataRequest) ProtoMessage() {}

func (x *SyncHealthDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncHealthDataRequest.ProtoReflect.Descriptor instead.
func (*SyncHealthDataRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *SyncHealthDataRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SyncHealthDataRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SyncHealthDataRequest) GetSleep() *SleepData {
	if x != nil {
		return x.Sleep
	}
	return nil
}

func (x *SyncHealthDataRequest) GetActivity() *ActivityData {
	if x != nil {
		return x.Activity
	}
	return nil
}

type SleepData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalHours    float32                `protobuf:"fixed32,1,opt,name=total_hours,json=totalHours,proto3" json:"total_hours,omitempty"`       // Общая продолжительность сна
	DeepSleepMin  string                 `protobuf:"bytes,2,opt,name=deep_sleep_min,json=deepSleepMin,proto3" json:"deep_sleep_min,omitempty"` // При желании можно расширять (глубокий сон)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SleepData) Reset() {
	*x = SleepData{}
	mi := &file_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepData) ProtoMessage() {}

func (x *SleepData) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepData.ProtoReflect.Descriptor instead.
func (*SleepData) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *SleepData) GetTotalHours() float32 {
	if x != nil {
		return x.TotalHours
	}
	return 0
}

func (x *SleepData) GetDeepSleepMin() string {
	if x != nil {
		return x.DeepSleepMin
	}
	return ""
}

type ActivityData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Steps          int32                  `protobuf:"varint,1,opt,name=steps,proto3" json:"steps,omitempty"`                                         // Шаги за день
	ActiveCalories int32                  `protobuf:"varint,2,opt,name=active_calories,json=activeCalories,proto3" json:"active_calories,omitempty"` // Сожженные калории
	WorkoutDone    bool                   `protobuf:"varint,3,opt,name=workout_done,json=workoutDone,proto3" json:"workout_done,omitempty"`          // Был ли зафиксирован воркаут
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActivityData) Reset() {
	*x = ActivityData{}
	mi := &file_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityData) ProtoMessage() {}

func (x *ActivityData) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityData.ProtoReflect.Descriptor instead.
func (*ActivityData) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *ActivityData) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

func (x *ActivityData) GetActiveCalories() int32 {
	if x != nil {
		return x.ActiveCalories
	}
	return 0
}

func (x *ActivityData) GetWorkoutDone() bool {
	if x != nil {
		return x.WorkoutDone
	}
	return false
}

type SyncHealthDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncHealthDataResponse) Reset() {
	*x = SyncHealthDataResponse{}
	mi := &file_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncHealthDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncHealthDataResponse) ProtoMessage() {}

func (x *SyncHealthDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncHealthDataResponse.ProtoReflect.Descriptor instead.
func (*SyncHealthDataResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *SyncHealthDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncHealthDataResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_tracker_proto protoreflect.FileDescriptor

const file_tracker_proto_rawDesc = "" +
	"\n" +
	"\rtracker.proto\x12\atracker\"\xa5\x01\n" +
	"\x15SyncHealthDataRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12(\n" +
	"\x05sleep\x18\x03 \x01(\v2\x12.tracker.SleepDataR\x05sleep\x121\n" +
	"\bactivity\x18\x04 \x01(\v2\x15.tracker.ActivityDataR\bactivity\"R\n" +
	"\tSleepData\x12\x1f\n" +
	"\vtotal_hours\x18\x01 \x01(\x02R\n" +
	"totalHours\x12$\n" +
	"\x0edeep_sleep_min\x18\x02 \x01(\tR\fdeepSleepMin\"p\n" +
	"\fActivityData\x12\x14\n" +
	"\x05steps\x18\x01 \x01(\x05R\x05steps\x12'\n" +
	"\x0factive_calories\x18\x02 \x01(\x05R\x0eactiveCalories\x12!\n" +
	"\fworkout_done\x18\x03 \x01(\bR\vworkoutDone\"W\n" +
	"\x16SyncHealthDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2c\n" +
	"\x0eTrackerService\x12Q\n" +
	"\x0eSyncHealthData\x12\x1e.tracker.SyncHealthDataRequest\x1a\x1f.tracker.SyncHealthDataResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_tracker_proto_rawDescOnce sync.Once
	file_tracker_proto_rawDescData []byte
)

func file_tracker_proto_rawDescGZIP() []byte {
	file_tracker_proto_rawDescOnce.Do(func() {
		file_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)))
	})
	return file_tracker_proto_rawDescData
}

var file_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tracker_proto_goTypes = []any{
	(*SyncHealthDataRequest)(nil),  // 0: tracker.SyncHealthDataRequest
	(*SleepData)(nil),              // 1: tracker.SleepData
	(*ActivityData)(nil),           // 2: tracker.ActivityData
	(*SyncHealthDataResponse)(nil), // 3: tracker.SyncHealthDataResponse
}
var file_tracker_proto_depIdxs = []int32{
	1, // 0: tracker.SyncHealthDataRequest.sleep:type_name -> tracker.SleepData
	2, // 1: tracker.SyncHealthDataRequest.activity:type_name -> tracker.ActivityData
	0, // 2: tracker.TrackerService.SyncHealthData:input_type -> tracker.SyncHealthDataRequest
	3, // 3: tracker.TrackerService.SyncHealthData:output_type -> tracker.SyncHealthDataResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tracker_proto_init() }
func file_tracker_proto_init() {
	if File_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracker_proto_goTypes,
		DependencyIndexes: file_tracker_proto_depIdxs,
		MessageInfos:      file_tracker_proto_msgTypes,
	}.Build()
	File_tracker_proto = out.File
	file_tracker_proto_goTypes = nil
	file_tracker_proto_depIdxs = nil
}
